Deduplicate errno values in errno2name()
On Darwin, the EQFULL and ELAST error constants lead to the same errno
value (106), so we get a build error like this:

  src/errno_list.cc:228:14: error: duplicate case value '106'
        case 106: return "EQFULL";
             ^
  src/errno_list.cc:227:14: note: previous case defined here
        case 106: return "ELAST";
             ^

We can simply throw away the duplicate values, because all that
errno2name is used for is printing the current rules with the -p command
line argument.

Signed-off-by: aszlig <aszlig@nix.build>